### ISSUE TITLE
Integration of Database with the project

### ISSUE THREAD

**Issue by bhavika2502** [upes-open/OSoC-Vaccination-Recording-System#14]

**Comment by GaganChaudhary6378** [comment]
Hi, I want to work on this issue.

**Comment by bhavika2502** [comment]
Sure! I'll assign you the project

**Comment by bhavika2502** [comment]
Hi @GaganChaudhary6378 Whats the update ?

**Comment by avnigoyal25** [comment]
hey i can work on this issue

**Comment by bhavika2502** [comment]
Sure @avnigoyal25 you may start working , I will assign it to you

**Comment by bhavika2502** [comment]
MongoDB has been integrated with node project, I am closing this issue

**Comment by bhavika2502** [comment]
Creating shared DB cluster and integrating that with project

**Comment by GaganChaudhary6378** [comment]
Just share the credentials of the Database ,I will do that.
