### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bhavika2502** [upes-open/OSoC-Vaccination-Recording-System#16]

**Comment by Shivansh175** [comment]
Hey! A beginner here! Can you explain a bit about what can be done under documentation

**Comment by avnigoyal25** [comment]
i can work on this issue.

**Comment by bhavika2502** [comment]
Hi @Shivansh175 
The documentation will require the following points about the project:
1. About the project
2. Uniqueness of the project
3. Who can use the product
4. Tech stack used
5. Contributors
6. Future scopes of the project

But these will vary and need to be taken up during the last week of OSoC. But you can create a draft for the same.

**Comment by bhavika2502** [comment]
@Shivansh175 Let me know if you wish to be assigned to this issue as well.

**Comment by bhavika2502** [comment]
@Shivansh175 @avnigoyal25 What's the update on documentation??

**Comment by avnigoyal25** [comment]
You told that it will be done in the last week of OSOC?

**Comment by bhavika2502** [comment]
@avnigoyal25 you can create a draft and PR for the same, we can update it

**Comment by avnigoyal25** [comment]
Okay will do it today then
