### ISSUE TITLE
Create UI Design for Dashboard

### ISSUE THREAD

**Issue by bhavika2502** [upes-open/OSoC-Vaccination-Recording-System#2]

**Comment by AmanKumarVlgs** [comment]
Hey @bhavika2502, I want to work on this issue. Please assign me this

**Comment by bhavika2502** [comment]
Sure @AmanKumarVlgs You may start working on this issue

**Comment by AmanKumarVlgs** [comment]
Thank you for assigning me this, I'll get back to you ASAP.
