### ISSUE TITLE
Create Landing Page to login/signup

### ISSUE THREAD

**Issue by bhavika2502** [upes-open/OSoC-Vaccination-Recording-System#5]

**Comment by Kruthardh11** [comment]
I would like to take this up. Please, assign this to me

**Comment by bhavika2502** [comment]
Sure! @Kruthardh11 You can start working on this issue

**Comment by priii-25** [comment]
Can I work on this issue?

**Comment by Shivansh175** [comment]
Can I work on this issue as well ?
Is there any UI provided or it is to be designed by our own?

**Comment by virajp4** [comment]
i would like to work on this issue @bhavika2502

**Comment by bhavika2502** [comment]
@Shivansh175 UI is provided but you are free to add ur own creativity
