### ISSUE TITLE
Create Dashboard for user to check records

### ISSUE THREAD

**Issue by bhavika2502** [upes-open/OSoC-Vaccination-Recording-System#6]

**Comment by H-SM** [comment]
Can I take up this issue?

**Comment by charan1409** [comment]
I want to resolve this issue.
And I have to create an page with filter for user records like searching an record out of all user's records or something else?

**Comment by bhavika2502** [comment]
Yes. you can work on this issue @charan1409

**Comment by jason2000-cpu** [comment]
I would like to work on this issue

**Comment by jason2000-cpu** [comment]
@bhavika2502  I have created a pr on this issue. Please check it out and give feedback

**Comment by bhavika2502** [comment]
Sure, I have merged your PR @jason2000-cpu . Great work!
