### ISSUE TITLE
Add dark and light theme switch

### ISSUE THREAD

**Issue by bhavika2502** [upes-open/OSoC-Vaccination-Recording-System#9]

**Comment by tarunvenkat** [comment]
Hey  @bhavika2502 I want to take up the issue please

**Comment by bhavika2502** [comment]
Sure! You can start working on this issue @tarunvenkat @H-SM

**Comment by priii-25** [comment]
can I take up this issue?

**Comment by Charu-2718** [comment]
Can I work on this issue?

**Comment by bhavika2502** [comment]
Sure @Charu-2718 Assigning you the issue

**Comment by Charu-2718** [comment]
#30 
Theme Added
